/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helloworld */

#ifndef _Included_helloworld
#define _Included_helloworld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloworld
 * Method:    getline
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helloworld_getline
  (JNIEnv *, jobject, jstring);

/*
 * Class:     helloworld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_helloworld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
